### ISSUE TITLE
URLs in settings keep resetting to localhost

### ISSUE THREAD

**Issue by unikitty37** [baretto-labs/OllamAssist#110]
My Ollama instance is at `http://192.168.1.12:11434`. I have changed the URLs in Other Settings > OllamaAssist to this.

However, when I change any OllamAssist settings, they are not saved — the "Apply" button does not become enabled, and hitting OK does not persist them. If I change to another settings category and change a setting there as well, the Apply button becomes enabled, but while _that_ setting is changed, the OllamAssist settings do not change.

Nothing in ~/.config/JetBrains/RubyMine 2025.2 is read-only. The options file doesn't contain my changes:

```xml
<application>
  <component name="OllamAssist">
    <option name="chatModelName" value="qwen2.5-coder:latest" />
    <option name="completionModelName" value="qwen2.5-coder:latest" />
  </component>
</application>
```

If I quit RubyMine and edit this file to add the URL settings manually, it can find Ollama — but still can't find qwen2.5-coder, because it's not installed any more. If I manually change the qwen2.5-coder entries to qwen3-coder (which _is_ installed) RubyMine crashes on startup.

Do you have any idea what might be going on here? 

## To reproduce

* Ensure Ollama is running on port 11434 on 192.168.1.12 and that OLLAMA_HOST is set to `0.0.0.0:11434`
* Open Settings
* Click on Other Settings > OllamAssist
* Change the three URLS from `http://localhost:11434` to `http://192.168.1.12:11434`
* Click OK
* Open Settings
* Click on Other Settings > OllamAssist

## Expected behaviour

When the first URL is changed, the Apply button becomes enabled. 
When the settings are viewed a second time, the change has persisted.
When the OllamAssist check is rerun, it notices that it can now talk to Ollama and stops complaining that it can't.
I can use OllamAssist and verify if #96 is now working for me :)

## Actual behaviour

The Apply button becomes enabled only when a non-OllamAssist setting is changed.
When the settings are viewed a second time, the URLs are all still pointing at localhost.
When the check is rerun, it continues to not find Ollama, because it is not looking in the right place.
I cannot use OllamAssist.

## Notes

When OllamAssist is installed, Settings > Other Settings seems to sit at "loading..." for several seconds before rendering. Without OllamAssist installed, it's instant.

**Comment by mehdi-elke** [comment]
Hi @unikitty37 ,

Thank you very much for the detailed report and for taking the time to describe the steps and expected behavior. This is extremely helpful.

I’ve started looking into the issue and will work on a fix to ensure that OllamAssist properly saves the URL settings and handles model validation. I’ll keep you updated once I have progress or a patch ready.

Thanks again for your report and patience!

Best regards,
Mehdi

**Comment by mehdi-elke** [comment]
Hi @unikitty37 ,

Here is the download link for the next version. Before releasing it on the marketplace, could you please test it to verify that the bug has been fixed?
https://drive.google.com/file/d/1zOu88Lbz4fZE-sh6MweOUtw_Dov6ze7v/view?usp=drive_link

Thank you very much.

For the installation, you can follow this guide: https://www.jetbrains.com/help/mps/managing-plugins.html#install_plugin_from_disk

Once again, thank you for your feedback, and please don’t hesitate to share any comments or suggestions—I’ll do my best to address them.

**Comment by joshkapple** [comment]
I'm running into the same issue with hostnames not saving and the apply button not becoming enabled. I installed the google drive linked version that downloads as `OllamAssist-1.5.0.zip` and saving hostnames is still not working. I've also tried the latest version `1.7.0` from marketplace and having the same issue.

**Comment by mehdi-elke** [comment]
Hi @joshkapple 

Thanks a lot for confirming and for taking the time to test the different versions.
I’m currently investigating the issue and hope to have a lead soon.
If you’re okay with it, I might share a ZIP build here first — it’s quicker to test than going through the Marketplace release process.

I’ll let you know as soon as there’s something new to try. Thanks again for your patience and help!

**Comment by mehdi-elke** [comment]
Hi @joshkapple and @unikitty37 


Thanks a lot for confirming and for taking the time to test the previous versions.
I’ve just prepared a new release after refactoring the settings change detection system — you can find it here:
 [v1.7.1](https://github.com/baretto-labs/OllamAssist/releases/tag/1.7.1)

You can grab the ZIP to test and validate the changes. If everything works for you, I can then push this version to the Marketplace.

Thanks again for your patience and for helping improve the plugin!

Mehdi

**Comment by joshkapple** [comment]
Hi @mehdi-elke, thanks for the quick turnaround and release on a fix. Sorry for the delay, took me a minute to get a working local build. I can confirm that v1.7.1 fixed the issues I was having and that the 'apply' button is enabled and saving appears to be working for me. Thanks!
